/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as ReferentenRouteImport } from './routes/referenten'
import { Route as NeulandRouteImport } from './routes/neuland'
import { Route as MitgliederRouteImport } from './routes/mitglieder'
import { Route as MitgliedWerdenRouteImport } from './routes/mitglied-werden'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VereinIndexRouteImport } from './routes/verein.index'
import { Route as ProgrammIndexRouteImport } from './routes/programm.index'
import { Route as NeulandIndexRouteImport } from './routes/neuland.index'
import { Route as VereinVorstandRouteImport } from './routes/verein.vorstand'
import { Route as VereinSatzungRouteImport } from './routes/verein.satzung'
import { Route as VereinBeiratRouteImport } from './routes/verein.beirat'
import { Route as ProgrammSlugRouteImport } from './routes/programm.$slug'
import { Route as NeulandWettbewerbRouteImport } from './routes/neuland.wettbewerb'
import { Route as NeulandTeilnahmeRouteImport } from './routes/neuland.teilnahme'
import { Route as NeulandPresseRouteImport } from './routes/neuland.presse'
import { Route as NeulandJuryRouteImport } from './routes/neuland.jury'
import { Route as NeulandGewinnerIndexRouteImport } from './routes/neuland.gewinner.index'
import { Route as NeulandGewinnerJahrIndexRouteImport } from './routes/neuland.gewinner.$jahr.index'
import { Route as NeulandGewinnerJahrSlugRouteImport } from './routes/neuland.gewinner.$jahr.$slug'

const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferentenRoute = ReferentenRouteImport.update({
  id: '/referenten',
  path: '/referenten',
  getParentRoute: () => rootRouteImport,
} as any)
const NeulandRoute = NeulandRouteImport.update({
  id: '/neuland',
  path: '/neuland',
  getParentRoute: () => rootRouteImport,
} as any)
const MitgliederRoute = MitgliederRouteImport.update({
  id: '/mitglieder',
  path: '/mitglieder',
  getParentRoute: () => rootRouteImport,
} as any)
const MitgliedWerdenRoute = MitgliedWerdenRouteImport.update({
  id: '/mitglied-werden',
  path: '/mitglied-werden',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VereinIndexRoute = VereinIndexRouteImport.update({
  id: '/verein/',
  path: '/verein/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammIndexRoute = ProgrammIndexRouteImport.update({
  id: '/programm/',
  path: '/programm/',
  getParentRoute: () => rootRouteImport,
} as any)
const NeulandIndexRoute = NeulandIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NeulandRoute,
} as any)
const VereinVorstandRoute = VereinVorstandRouteImport.update({
  id: '/verein/vorstand',
  path: '/verein/vorstand',
  getParentRoute: () => rootRouteImport,
} as any)
const VereinSatzungRoute = VereinSatzungRouteImport.update({
  id: '/verein/satzung',
  path: '/verein/satzung',
  getParentRoute: () => rootRouteImport,
} as any)
const VereinBeiratRoute = VereinBeiratRouteImport.update({
  id: '/verein/beirat',
  path: '/verein/beirat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammSlugRoute = ProgrammSlugRouteImport.update({
  id: '/programm/$slug',
  path: '/programm/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NeulandWettbewerbRoute = NeulandWettbewerbRouteImport.update({
  id: '/wettbewerb',
  path: '/wettbewerb',
  getParentRoute: () => NeulandRoute,
} as any)
const NeulandTeilnahmeRoute = NeulandTeilnahmeRouteImport.update({
  id: '/teilnahme',
  path: '/teilnahme',
  getParentRoute: () => NeulandRoute,
} as any)
const NeulandPresseRoute = NeulandPresseRouteImport.update({
  id: '/presse',
  path: '/presse',
  getParentRoute: () => NeulandRoute,
} as any)
const NeulandJuryRoute = NeulandJuryRouteImport.update({
  id: '/jury',
  path: '/jury',
  getParentRoute: () => NeulandRoute,
} as any)
const NeulandGewinnerIndexRoute = NeulandGewinnerIndexRouteImport.update({
  id: '/gewinner/',
  path: '/gewinner/',
  getParentRoute: () => NeulandRoute,
} as any)
const NeulandGewinnerJahrIndexRoute =
  NeulandGewinnerJahrIndexRouteImport.update({
    id: '/gewinner/$jahr/',
    path: '/gewinner/$jahr/',
    getParentRoute: () => NeulandRoute,
  } as any)
const NeulandGewinnerJahrSlugRoute = NeulandGewinnerJahrSlugRouteImport.update({
  id: '/gewinner/$jahr/$slug',
  path: '/gewinner/$jahr/$slug',
  getParentRoute: () => NeulandRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/mitglied-werden': typeof MitgliedWerdenRoute
  '/mitglieder': typeof MitgliederRoute
  '/neuland': typeof NeulandRouteWithChildren
  '/referenten': typeof ReferentenRoute
  '/service': typeof ServiceRoute
  '/neuland/jury': typeof NeulandJuryRoute
  '/neuland/presse': typeof NeulandPresseRoute
  '/neuland/teilnahme': typeof NeulandTeilnahmeRoute
  '/neuland/wettbewerb': typeof NeulandWettbewerbRoute
  '/programm/$slug': typeof ProgrammSlugRoute
  '/verein/beirat': typeof VereinBeiratRoute
  '/verein/satzung': typeof VereinSatzungRoute
  '/verein/vorstand': typeof VereinVorstandRoute
  '/neuland/': typeof NeulandIndexRoute
  '/programm/': typeof ProgrammIndexRoute
  '/verein/': typeof VereinIndexRoute
  '/neuland/gewinner/': typeof NeulandGewinnerIndexRoute
  '/neuland/gewinner/$jahr/$slug': typeof NeulandGewinnerJahrSlugRoute
  '/neuland/gewinner/$jahr/': typeof NeulandGewinnerJahrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/mitglied-werden': typeof MitgliedWerdenRoute
  '/mitglieder': typeof MitgliederRoute
  '/referenten': typeof ReferentenRoute
  '/service': typeof ServiceRoute
  '/neuland/jury': typeof NeulandJuryRoute
  '/neuland/presse': typeof NeulandPresseRoute
  '/neuland/teilnahme': typeof NeulandTeilnahmeRoute
  '/neuland/wettbewerb': typeof NeulandWettbewerbRoute
  '/programm/$slug': typeof ProgrammSlugRoute
  '/verein/beirat': typeof VereinBeiratRoute
  '/verein/satzung': typeof VereinSatzungRoute
  '/verein/vorstand': typeof VereinVorstandRoute
  '/neuland': typeof NeulandIndexRoute
  '/programm': typeof ProgrammIndexRoute
  '/verein': typeof VereinIndexRoute
  '/neuland/gewinner': typeof NeulandGewinnerIndexRoute
  '/neuland/gewinner/$jahr/$slug': typeof NeulandGewinnerJahrSlugRoute
  '/neuland/gewinner/$jahr': typeof NeulandGewinnerJahrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/mitglied-werden': typeof MitgliedWerdenRoute
  '/mitglieder': typeof MitgliederRoute
  '/neuland': typeof NeulandRouteWithChildren
  '/referenten': typeof ReferentenRoute
  '/service': typeof ServiceRoute
  '/neuland/jury': typeof NeulandJuryRoute
  '/neuland/presse': typeof NeulandPresseRoute
  '/neuland/teilnahme': typeof NeulandTeilnahmeRoute
  '/neuland/wettbewerb': typeof NeulandWettbewerbRoute
  '/programm/$slug': typeof ProgrammSlugRoute
  '/verein/beirat': typeof VereinBeiratRoute
  '/verein/satzung': typeof VereinSatzungRoute
  '/verein/vorstand': typeof VereinVorstandRoute
  '/neuland/': typeof NeulandIndexRoute
  '/programm/': typeof ProgrammIndexRoute
  '/verein/': typeof VereinIndexRoute
  '/neuland/gewinner/': typeof NeulandGewinnerIndexRoute
  '/neuland/gewinner/$jahr/$slug': typeof NeulandGewinnerJahrSlugRoute
  '/neuland/gewinner/$jahr/': typeof NeulandGewinnerJahrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/mitglied-werden'
    | '/mitglieder'
    | '/neuland'
    | '/referenten'
    | '/service'
    | '/neuland/jury'
    | '/neuland/presse'
    | '/neuland/teilnahme'
    | '/neuland/wettbewerb'
    | '/programm/$slug'
    | '/verein/beirat'
    | '/verein/satzung'
    | '/verein/vorstand'
    | '/neuland/'
    | '/programm/'
    | '/verein/'
    | '/neuland/gewinner/'
    | '/neuland/gewinner/$jahr/$slug'
    | '/neuland/gewinner/$jahr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/mitglied-werden'
    | '/mitglieder'
    | '/referenten'
    | '/service'
    | '/neuland/jury'
    | '/neuland/presse'
    | '/neuland/teilnahme'
    | '/neuland/wettbewerb'
    | '/programm/$slug'
    | '/verein/beirat'
    | '/verein/satzung'
    | '/verein/vorstand'
    | '/neuland'
    | '/programm'
    | '/verein'
    | '/neuland/gewinner'
    | '/neuland/gewinner/$jahr/$slug'
    | '/neuland/gewinner/$jahr'
  id:
    | '__root__'
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/kontakt'
    | '/mitglied-werden'
    | '/mitglieder'
    | '/neuland'
    | '/referenten'
    | '/service'
    | '/neuland/jury'
    | '/neuland/presse'
    | '/neuland/teilnahme'
    | '/neuland/wettbewerb'
    | '/programm/$slug'
    | '/verein/beirat'
    | '/verein/satzung'
    | '/verein/vorstand'
    | '/neuland/'
    | '/programm/'
    | '/verein/'
    | '/neuland/gewinner/'
    | '/neuland/gewinner/$jahr/$slug'
    | '/neuland/gewinner/$jahr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  MitgliedWerdenRoute: typeof MitgliedWerdenRoute
  MitgliederRoute: typeof MitgliederRoute
  NeulandRoute: typeof NeulandRouteWithChildren
  ReferentenRoute: typeof ReferentenRoute
  ServiceRoute: typeof ServiceRoute
  ProgrammSlugRoute: typeof ProgrammSlugRoute
  VereinBeiratRoute: typeof VereinBeiratRoute
  VereinSatzungRoute: typeof VereinSatzungRoute
  VereinVorstandRoute: typeof VereinVorstandRoute
  ProgrammIndexRoute: typeof ProgrammIndexRoute
  VereinIndexRoute: typeof VereinIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referenten': {
      id: '/referenten'
      path: '/referenten'
      fullPath: '/referenten'
      preLoaderRoute: typeof ReferentenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neuland': {
      id: '/neuland'
      path: '/neuland'
      fullPath: '/neuland'
      preLoaderRoute: typeof NeulandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitglieder': {
      id: '/mitglieder'
      path: '/mitglieder'
      fullPath: '/mitglieder'
      preLoaderRoute: typeof MitgliederRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitglied-werden': {
      id: '/mitglied-werden'
      path: '/mitglied-werden'
      fullPath: '/mitglied-werden'
      preLoaderRoute: typeof MitgliedWerdenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verein/': {
      id: '/verein/'
      path: '/verein'
      fullPath: '/verein/'
      preLoaderRoute: typeof VereinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programm/': {
      id: '/programm/'
      path: '/programm'
      fullPath: '/programm/'
      preLoaderRoute: typeof ProgrammIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neuland/': {
      id: '/neuland/'
      path: '/'
      fullPath: '/neuland/'
      preLoaderRoute: typeof NeulandIndexRouteImport
      parentRoute: typeof NeulandRoute
    }
    '/verein/vorstand': {
      id: '/verein/vorstand'
      path: '/verein/vorstand'
      fullPath: '/verein/vorstand'
      preLoaderRoute: typeof VereinVorstandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verein/satzung': {
      id: '/verein/satzung'
      path: '/verein/satzung'
      fullPath: '/verein/satzung'
      preLoaderRoute: typeof VereinSatzungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verein/beirat': {
      id: '/verein/beirat'
      path: '/verein/beirat'
      fullPath: '/verein/beirat'
      preLoaderRoute: typeof VereinBeiratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programm/$slug': {
      id: '/programm/$slug'
      path: '/programm/$slug'
      fullPath: '/programm/$slug'
      preLoaderRoute: typeof ProgrammSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neuland/wettbewerb': {
      id: '/neuland/wettbewerb'
      path: '/wettbewerb'
      fullPath: '/neuland/wettbewerb'
      preLoaderRoute: typeof NeulandWettbewerbRouteImport
      parentRoute: typeof NeulandRoute
    }
    '/neuland/teilnahme': {
      id: '/neuland/teilnahme'
      path: '/teilnahme'
      fullPath: '/neuland/teilnahme'
      preLoaderRoute: typeof NeulandTeilnahmeRouteImport
      parentRoute: typeof NeulandRoute
    }
    '/neuland/presse': {
      id: '/neuland/presse'
      path: '/presse'
      fullPath: '/neuland/presse'
      preLoaderRoute: typeof NeulandPresseRouteImport
      parentRoute: typeof NeulandRoute
    }
    '/neuland/jury': {
      id: '/neuland/jury'
      path: '/jury'
      fullPath: '/neuland/jury'
      preLoaderRoute: typeof NeulandJuryRouteImport
      parentRoute: typeof NeulandRoute
    }
    '/neuland/gewinner/': {
      id: '/neuland/gewinner/'
      path: '/gewinner'
      fullPath: '/neuland/gewinner/'
      preLoaderRoute: typeof NeulandGewinnerIndexRouteImport
      parentRoute: typeof NeulandRoute
    }
    '/neuland/gewinner/$jahr/': {
      id: '/neuland/gewinner/$jahr/'
      path: '/gewinner/$jahr'
      fullPath: '/neuland/gewinner/$jahr/'
      preLoaderRoute: typeof NeulandGewinnerJahrIndexRouteImport
      parentRoute: typeof NeulandRoute
    }
    '/neuland/gewinner/$jahr/$slug': {
      id: '/neuland/gewinner/$jahr/$slug'
      path: '/gewinner/$jahr/$slug'
      fullPath: '/neuland/gewinner/$jahr/$slug'
      preLoaderRoute: typeof NeulandGewinnerJahrSlugRouteImport
      parentRoute: typeof NeulandRoute
    }
  }
}

interface NeulandRouteChildren {
  NeulandJuryRoute: typeof NeulandJuryRoute
  NeulandPresseRoute: typeof NeulandPresseRoute
  NeulandTeilnahmeRoute: typeof NeulandTeilnahmeRoute
  NeulandWettbewerbRoute: typeof NeulandWettbewerbRoute
  NeulandIndexRoute: typeof NeulandIndexRoute
  NeulandGewinnerIndexRoute: typeof NeulandGewinnerIndexRoute
  NeulandGewinnerJahrSlugRoute: typeof NeulandGewinnerJahrSlugRoute
  NeulandGewinnerJahrIndexRoute: typeof NeulandGewinnerJahrIndexRoute
}

const NeulandRouteChildren: NeulandRouteChildren = {
  NeulandJuryRoute: NeulandJuryRoute,
  NeulandPresseRoute: NeulandPresseRoute,
  NeulandTeilnahmeRoute: NeulandTeilnahmeRoute,
  NeulandWettbewerbRoute: NeulandWettbewerbRoute,
  NeulandIndexRoute: NeulandIndexRoute,
  NeulandGewinnerIndexRoute: NeulandGewinnerIndexRoute,
  NeulandGewinnerJahrSlugRoute: NeulandGewinnerJahrSlugRoute,
  NeulandGewinnerJahrIndexRoute: NeulandGewinnerJahrIndexRoute,
}

const NeulandRouteWithChildren =
  NeulandRoute._addFileChildren(NeulandRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  MitgliedWerdenRoute: MitgliedWerdenRoute,
  MitgliederRoute: MitgliederRoute,
  NeulandRoute: NeulandRouteWithChildren,
  ReferentenRoute: ReferentenRoute,
  ServiceRoute: ServiceRoute,
  ProgrammSlugRoute: ProgrammSlugRoute,
  VereinBeiratRoute: VereinBeiratRoute,
  VereinSatzungRoute: VereinSatzungRoute,
  VereinVorstandRoute: VereinVorstandRoute,
  ProgrammIndexRoute: ProgrammIndexRoute,
  VereinIndexRoute: VereinIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
