/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiceRouteImport } from './routes/service'
import { Route as ReferentenRouteImport } from './routes/referenten'
import { Route as NeulandRouteImport } from './routes/neuland'
import { Route as MitgliederRouteImport } from './routes/mitglieder'
import { Route as MitgliedWerdenRouteImport } from './routes/mitglied-werden'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as JuryRouteImport } from './routes/jury'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VereinIndexRouteImport } from './routes/verein.index'
import { Route as ProgrammIndexRouteImport } from './routes/programm.index'
import { Route as NeulandIndexRouteImport } from './routes/neuland.index'
import { Route as VereinVorstandRouteImport } from './routes/verein.vorstand'
import { Route as VereinSatzungRouteImport } from './routes/verein.satzung'
import { Route as VereinMitgliedWerdenRouteImport } from './routes/verein.mitglied-werden'
import { Route as VereinBeiratRouteImport } from './routes/verein.beirat'
import { Route as ProgrammSlugRouteImport } from './routes/programm.$slug'
import { Route as NeulandWettbewerbRouteImport } from './routes/neuland.wettbewerb'
import { Route as NeulandTeilnahmeRouteImport } from './routes/neuland.teilnahme'
import { Route as NeulandPresseRouteImport } from './routes/neuland.presse'
import { Route as NeulandJuryRouteImport } from './routes/neuland.jury'
import { Route as NeulandGewinnerInnenJahrRouteImport } from './routes/neuland.gewinner-innen-$jahr'
import { Route as Neuland1SplatRouteImport } from './routes/neuland-1.$'
import { Route as MitgliederFoerdermitgliederRouteImport } from './routes/mitglieder.foerdermitglieder'
import { Route as VereinVorstandIndexRouteImport } from './routes/verein.vorstand.index'
import { Route as VereinBeiratIndexRouteImport } from './routes/verein.beirat.index'
import { Route as NeulandGewinnerIndexRouteImport } from './routes/neuland.gewinner.index'
import { Route as NeulandGewinnerJahrIndexRouteImport } from './routes/neuland.gewinner.$jahr.index'
import { Route as NeulandGewinnerJahrSlugRouteImport } from './routes/neuland.gewinner.$jahr.$slug'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceRoute = ServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferentenRoute = ReferentenRouteImport.update({
  id: '/referenten',
  path: '/referenten',
  getParentRoute: () => rootRouteImport,
} as any)
const NeulandRoute = NeulandRouteImport.update({
  id: '/neuland',
  path: '/neuland',
  getParentRoute: () => rootRouteImport,
} as any)
const MitgliederRoute = MitgliederRouteImport.update({
  id: '/mitglieder',
  path: '/mitglieder',
  getParentRoute: () => rootRouteImport,
} as any)
const MitgliedWerdenRoute = MitgliedWerdenRouteImport.update({
  id: '/mitglied-werden',
  path: '/mitglied-werden',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const JuryRoute = JuryRouteImport.update({
  id: '/jury',
  path: '/jury',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VereinIndexRoute = VereinIndexRouteImport.update({
  id: '/verein/',
  path: '/verein/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammIndexRoute = ProgrammIndexRouteImport.update({
  id: '/programm/',
  path: '/programm/',
  getParentRoute: () => rootRouteImport,
} as any)
const NeulandIndexRoute = NeulandIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NeulandRoute,
} as any)
const VereinVorstandRoute = VereinVorstandRouteImport.update({
  id: '/verein/vorstand',
  path: '/verein/vorstand',
  getParentRoute: () => rootRouteImport,
} as any)
const VereinSatzungRoute = VereinSatzungRouteImport.update({
  id: '/verein/satzung',
  path: '/verein/satzung',
  getParentRoute: () => rootRouteImport,
} as any)
const VereinMitgliedWerdenRoute = VereinMitgliedWerdenRouteImport.update({
  id: '/verein/mitglied-werden',
  path: '/verein/mitglied-werden',
  getParentRoute: () => rootRouteImport,
} as any)
const VereinBeiratRoute = VereinBeiratRouteImport.update({
  id: '/verein/beirat',
  path: '/verein/beirat',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammSlugRoute = ProgrammSlugRouteImport.update({
  id: '/programm/$slug',
  path: '/programm/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NeulandWettbewerbRoute = NeulandWettbewerbRouteImport.update({
  id: '/wettbewerb',
  path: '/wettbewerb',
  getParentRoute: () => NeulandRoute,
} as any)
const NeulandTeilnahmeRoute = NeulandTeilnahmeRouteImport.update({
  id: '/teilnahme',
  path: '/teilnahme',
  getParentRoute: () => NeulandRoute,
} as any)
const NeulandPresseRoute = NeulandPresseRouteImport.update({
  id: '/presse',
  path: '/presse',
  getParentRoute: () => NeulandRoute,
} as any)
const NeulandJuryRoute = NeulandJuryRouteImport.update({
  id: '/jury',
  path: '/jury',
  getParentRoute: () => NeulandRoute,
} as any)
const NeulandGewinnerInnenJahrRoute =
  NeulandGewinnerInnenJahrRouteImport.update({
    id: '/gewinner-innen-$jahr',
    path: '/gewinner-innen-$jahr',
    getParentRoute: () => NeulandRoute,
  } as any)
const Neuland1SplatRoute = Neuland1SplatRouteImport.update({
  id: '/neuland-1/$',
  path: '/neuland-1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MitgliederFoerdermitgliederRoute =
  MitgliederFoerdermitgliederRouteImport.update({
    id: '/foerdermitglieder',
    path: '/foerdermitglieder',
    getParentRoute: () => MitgliederRoute,
  } as any)
const VereinVorstandIndexRoute = VereinVorstandIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VereinVorstandRoute,
} as any)
const VereinBeiratIndexRoute = VereinBeiratIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VereinBeiratRoute,
} as any)
const NeulandGewinnerIndexRoute = NeulandGewinnerIndexRouteImport.update({
  id: '/gewinner/',
  path: '/gewinner/',
  getParentRoute: () => NeulandRoute,
} as any)
const NeulandGewinnerJahrIndexRoute =
  NeulandGewinnerJahrIndexRouteImport.update({
    id: '/gewinner/$jahr/',
    path: '/gewinner/$jahr/',
    getParentRoute: () => NeulandRoute,
  } as any)
const NeulandGewinnerJahrSlugRoute = NeulandGewinnerJahrSlugRouteImport.update({
  id: '/gewinner/$jahr/$slug',
  path: '/gewinner/$jahr/$slug',
  getParentRoute: () => NeulandRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/jury': typeof JuryRoute
  '/kontakt': typeof KontaktRoute
  '/mitglied-werden': typeof MitgliedWerdenRoute
  '/mitglieder': typeof MitgliederRouteWithChildren
  '/neuland': typeof NeulandRouteWithChildren
  '/referenten': typeof ReferentenRoute
  '/service': typeof ServiceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unlock': typeof UnlockRoute
  '/mitglieder/foerdermitglieder': typeof MitgliederFoerdermitgliederRoute
  '/neuland-1/$': typeof Neuland1SplatRoute
  '/neuland/gewinner-innen-$jahr': typeof NeulandGewinnerInnenJahrRoute
  '/neuland/jury': typeof NeulandJuryRoute
  '/neuland/presse': typeof NeulandPresseRoute
  '/neuland/teilnahme': typeof NeulandTeilnahmeRoute
  '/neuland/wettbewerb': typeof NeulandWettbewerbRoute
  '/programm/$slug': typeof ProgrammSlugRoute
  '/verein/beirat': typeof VereinBeiratRouteWithChildren
  '/verein/mitglied-werden': typeof VereinMitgliedWerdenRoute
  '/verein/satzung': typeof VereinSatzungRoute
  '/verein/vorstand': typeof VereinVorstandRouteWithChildren
  '/neuland/': typeof NeulandIndexRoute
  '/programm/': typeof ProgrammIndexRoute
  '/verein/': typeof VereinIndexRoute
  '/neuland/gewinner/': typeof NeulandGewinnerIndexRoute
  '/verein/beirat/': typeof VereinBeiratIndexRoute
  '/verein/vorstand/': typeof VereinVorstandIndexRoute
  '/neuland/gewinner/$jahr/$slug': typeof NeulandGewinnerJahrSlugRoute
  '/neuland/gewinner/$jahr/': typeof NeulandGewinnerJahrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/jury': typeof JuryRoute
  '/kontakt': typeof KontaktRoute
  '/mitglied-werden': typeof MitgliedWerdenRoute
  '/mitglieder': typeof MitgliederRouteWithChildren
  '/referenten': typeof ReferentenRoute
  '/service': typeof ServiceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unlock': typeof UnlockRoute
  '/mitglieder/foerdermitglieder': typeof MitgliederFoerdermitgliederRoute
  '/neuland-1/$': typeof Neuland1SplatRoute
  '/neuland/gewinner-innen-$jahr': typeof NeulandGewinnerInnenJahrRoute
  '/neuland/jury': typeof NeulandJuryRoute
  '/neuland/presse': typeof NeulandPresseRoute
  '/neuland/teilnahme': typeof NeulandTeilnahmeRoute
  '/neuland/wettbewerb': typeof NeulandWettbewerbRoute
  '/programm/$slug': typeof ProgrammSlugRoute
  '/verein/mitglied-werden': typeof VereinMitgliedWerdenRoute
  '/verein/satzung': typeof VereinSatzungRoute
  '/neuland': typeof NeulandIndexRoute
  '/programm': typeof ProgrammIndexRoute
  '/verein': typeof VereinIndexRoute
  '/neuland/gewinner': typeof NeulandGewinnerIndexRoute
  '/verein/beirat': typeof VereinBeiratIndexRoute
  '/verein/vorstand': typeof VereinVorstandIndexRoute
  '/neuland/gewinner/$jahr/$slug': typeof NeulandGewinnerJahrSlugRoute
  '/neuland/gewinner/$jahr': typeof NeulandGewinnerJahrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/jury': typeof JuryRoute
  '/kontakt': typeof KontaktRoute
  '/mitglied-werden': typeof MitgliedWerdenRoute
  '/mitglieder': typeof MitgliederRouteWithChildren
  '/neuland': typeof NeulandRouteWithChildren
  '/referenten': typeof ReferentenRoute
  '/service': typeof ServiceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unlock': typeof UnlockRoute
  '/mitglieder/foerdermitglieder': typeof MitgliederFoerdermitgliederRoute
  '/neuland-1/$': typeof Neuland1SplatRoute
  '/neuland/gewinner-innen-$jahr': typeof NeulandGewinnerInnenJahrRoute
  '/neuland/jury': typeof NeulandJuryRoute
  '/neuland/presse': typeof NeulandPresseRoute
  '/neuland/teilnahme': typeof NeulandTeilnahmeRoute
  '/neuland/wettbewerb': typeof NeulandWettbewerbRoute
  '/programm/$slug': typeof ProgrammSlugRoute
  '/verein/beirat': typeof VereinBeiratRouteWithChildren
  '/verein/mitglied-werden': typeof VereinMitgliedWerdenRoute
  '/verein/satzung': typeof VereinSatzungRoute
  '/verein/vorstand': typeof VereinVorstandRouteWithChildren
  '/neuland/': typeof NeulandIndexRoute
  '/programm/': typeof ProgrammIndexRoute
  '/verein/': typeof VereinIndexRoute
  '/neuland/gewinner/': typeof NeulandGewinnerIndexRoute
  '/verein/beirat/': typeof VereinBeiratIndexRoute
  '/verein/vorstand/': typeof VereinVorstandIndexRoute
  '/neuland/gewinner/$jahr/$slug': typeof NeulandGewinnerJahrSlugRoute
  '/neuland/gewinner/$jahr/': typeof NeulandGewinnerJahrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/jury'
    | '/kontakt'
    | '/mitglied-werden'
    | '/mitglieder'
    | '/neuland'
    | '/referenten'
    | '/service'
    | '/sitemap.xml'
    | '/unlock'
    | '/mitglieder/foerdermitglieder'
    | '/neuland-1/$'
    | '/neuland/gewinner-innen-$jahr'
    | '/neuland/jury'
    | '/neuland/presse'
    | '/neuland/teilnahme'
    | '/neuland/wettbewerb'
    | '/programm/$slug'
    | '/verein/beirat'
    | '/verein/mitglied-werden'
    | '/verein/satzung'
    | '/verein/vorstand'
    | '/neuland/'
    | '/programm/'
    | '/verein/'
    | '/neuland/gewinner/'
    | '/verein/beirat/'
    | '/verein/vorstand/'
    | '/neuland/gewinner/$jahr/$slug'
    | '/neuland/gewinner/$jahr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/jury'
    | '/kontakt'
    | '/mitglied-werden'
    | '/mitglieder'
    | '/referenten'
    | '/service'
    | '/sitemap.xml'
    | '/unlock'
    | '/mitglieder/foerdermitglieder'
    | '/neuland-1/$'
    | '/neuland/gewinner-innen-$jahr'
    | '/neuland/jury'
    | '/neuland/presse'
    | '/neuland/teilnahme'
    | '/neuland/wettbewerb'
    | '/programm/$slug'
    | '/verein/mitglied-werden'
    | '/verein/satzung'
    | '/neuland'
    | '/programm'
    | '/verein'
    | '/neuland/gewinner'
    | '/verein/beirat'
    | '/verein/vorstand'
    | '/neuland/gewinner/$jahr/$slug'
    | '/neuland/gewinner/$jahr'
  id:
    | '__root__'
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/jury'
    | '/kontakt'
    | '/mitglied-werden'
    | '/mitglieder'
    | '/neuland'
    | '/referenten'
    | '/service'
    | '/sitemap.xml'
    | '/unlock'
    | '/mitglieder/foerdermitglieder'
    | '/neuland-1/$'
    | '/neuland/gewinner-innen-$jahr'
    | '/neuland/jury'
    | '/neuland/presse'
    | '/neuland/teilnahme'
    | '/neuland/wettbewerb'
    | '/programm/$slug'
    | '/verein/beirat'
    | '/verein/mitglied-werden'
    | '/verein/satzung'
    | '/verein/vorstand'
    | '/neuland/'
    | '/programm/'
    | '/verein/'
    | '/neuland/gewinner/'
    | '/verein/beirat/'
    | '/verein/vorstand/'
    | '/neuland/gewinner/$jahr/$slug'
    | '/neuland/gewinner/$jahr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  JuryRoute: typeof JuryRoute
  KontaktRoute: typeof KontaktRoute
  MitgliedWerdenRoute: typeof MitgliedWerdenRoute
  MitgliederRoute: typeof MitgliederRouteWithChildren
  NeulandRoute: typeof NeulandRouteWithChildren
  ReferentenRoute: typeof ReferentenRoute
  ServiceRoute: typeof ServiceRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnlockRoute: typeof UnlockRoute
  Neuland1SplatRoute: typeof Neuland1SplatRoute
  ProgrammSlugRoute: typeof ProgrammSlugRoute
  VereinBeiratRoute: typeof VereinBeiratRouteWithChildren
  VereinMitgliedWerdenRoute: typeof VereinMitgliedWerdenRoute
  VereinSatzungRoute: typeof VereinSatzungRoute
  VereinVorstandRoute: typeof VereinVorstandRouteWithChildren
  ProgrammIndexRoute: typeof ProgrammIndexRoute
  VereinIndexRoute: typeof VereinIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service': {
      id: '/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof ServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referenten': {
      id: '/referenten'
      path: '/referenten'
      fullPath: '/referenten'
      preLoaderRoute: typeof ReferentenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neuland': {
      id: '/neuland'
      path: '/neuland'
      fullPath: '/neuland'
      preLoaderRoute: typeof NeulandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitglieder': {
      id: '/mitglieder'
      path: '/mitglieder'
      fullPath: '/mitglieder'
      preLoaderRoute: typeof MitgliederRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitglied-werden': {
      id: '/mitglied-werden'
      path: '/mitglied-werden'
      fullPath: '/mitglied-werden'
      preLoaderRoute: typeof MitgliedWerdenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jury': {
      id: '/jury'
      path: '/jury'
      fullPath: '/jury'
      preLoaderRoute: typeof JuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verein/': {
      id: '/verein/'
      path: '/verein'
      fullPath: '/verein/'
      preLoaderRoute: typeof VereinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programm/': {
      id: '/programm/'
      path: '/programm'
      fullPath: '/programm/'
      preLoaderRoute: typeof ProgrammIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neuland/': {
      id: '/neuland/'
      path: '/'
      fullPath: '/neuland/'
      preLoaderRoute: typeof NeulandIndexRouteImport
      parentRoute: typeof NeulandRoute
    }
    '/verein/vorstand': {
      id: '/verein/vorstand'
      path: '/verein/vorstand'
      fullPath: '/verein/vorstand'
      preLoaderRoute: typeof VereinVorstandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verein/satzung': {
      id: '/verein/satzung'
      path: '/verein/satzung'
      fullPath: '/verein/satzung'
      preLoaderRoute: typeof VereinSatzungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verein/mitglied-werden': {
      id: '/verein/mitglied-werden'
      path: '/verein/mitglied-werden'
      fullPath: '/verein/mitglied-werden'
      preLoaderRoute: typeof VereinMitgliedWerdenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verein/beirat': {
      id: '/verein/beirat'
      path: '/verein/beirat'
      fullPath: '/verein/beirat'
      preLoaderRoute: typeof VereinBeiratRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programm/$slug': {
      id: '/programm/$slug'
      path: '/programm/$slug'
      fullPath: '/programm/$slug'
      preLoaderRoute: typeof ProgrammSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neuland/wettbewerb': {
      id: '/neuland/wettbewerb'
      path: '/wettbewerb'
      fullPath: '/neuland/wettbewerb'
      preLoaderRoute: typeof NeulandWettbewerbRouteImport
      parentRoute: typeof NeulandRoute
    }
    '/neuland/teilnahme': {
      id: '/neuland/teilnahme'
      path: '/teilnahme'
      fullPath: '/neuland/teilnahme'
      preLoaderRoute: typeof NeulandTeilnahmeRouteImport
      parentRoute: typeof NeulandRoute
    }
    '/neuland/presse': {
      id: '/neuland/presse'
      path: '/presse'
      fullPath: '/neuland/presse'
      preLoaderRoute: typeof NeulandPresseRouteImport
      parentRoute: typeof NeulandRoute
    }
    '/neuland/jury': {
      id: '/neuland/jury'
      path: '/jury'
      fullPath: '/neuland/jury'
      preLoaderRoute: typeof NeulandJuryRouteImport
      parentRoute: typeof NeulandRoute
    }
    '/neuland/gewinner-innen-$jahr': {
      id: '/neuland/gewinner-innen-$jahr'
      path: '/gewinner-innen-$jahr'
      fullPath: '/neuland/gewinner-innen-$jahr'
      preLoaderRoute: typeof NeulandGewinnerInnenJahrRouteImport
      parentRoute: typeof NeulandRoute
    }
    '/neuland-1/$': {
      id: '/neuland-1/$'
      path: '/neuland-1/$'
      fullPath: '/neuland-1/$'
      preLoaderRoute: typeof Neuland1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitglieder/foerdermitglieder': {
      id: '/mitglieder/foerdermitglieder'
      path: '/foerdermitglieder'
      fullPath: '/mitglieder/foerdermitglieder'
      preLoaderRoute: typeof MitgliederFoerdermitgliederRouteImport
      parentRoute: typeof MitgliederRoute
    }
    '/verein/vorstand/': {
      id: '/verein/vorstand/'
      path: '/'
      fullPath: '/verein/vorstand/'
      preLoaderRoute: typeof VereinVorstandIndexRouteImport
      parentRoute: typeof VereinVorstandRoute
    }
    '/verein/beirat/': {
      id: '/verein/beirat/'
      path: '/'
      fullPath: '/verein/beirat/'
      preLoaderRoute: typeof VereinBeiratIndexRouteImport
      parentRoute: typeof VereinBeiratRoute
    }
    '/neuland/gewinner/': {
      id: '/neuland/gewinner/'
      path: '/gewinner'
      fullPath: '/neuland/gewinner/'
      preLoaderRoute: typeof NeulandGewinnerIndexRouteImport
      parentRoute: typeof NeulandRoute
    }
    '/neuland/gewinner/$jahr/': {
      id: '/neuland/gewinner/$jahr/'
      path: '/gewinner/$jahr'
      fullPath: '/neuland/gewinner/$jahr/'
      preLoaderRoute: typeof NeulandGewinnerJahrIndexRouteImport
      parentRoute: typeof NeulandRoute
    }
    '/neuland/gewinner/$jahr/$slug': {
      id: '/neuland/gewinner/$jahr/$slug'
      path: '/gewinner/$jahr/$slug'
      fullPath: '/neuland/gewinner/$jahr/$slug'
      preLoaderRoute: typeof NeulandGewinnerJahrSlugRouteImport
      parentRoute: typeof NeulandRoute
    }
  }
}

interface MitgliederRouteChildren {
  MitgliederFoerdermitgliederRoute: typeof MitgliederFoerdermitgliederRoute
}

const MitgliederRouteChildren: MitgliederRouteChildren = {
  MitgliederFoerdermitgliederRoute: MitgliederFoerdermitgliederRoute,
}

const MitgliederRouteWithChildren = MitgliederRoute._addFileChildren(
  MitgliederRouteChildren,
)

interface NeulandRouteChildren {
  NeulandGewinnerInnenJahrRoute: typeof NeulandGewinnerInnenJahrRoute
  NeulandJuryRoute: typeof NeulandJuryRoute
  NeulandPresseRoute: typeof NeulandPresseRoute
  NeulandTeilnahmeRoute: typeof NeulandTeilnahmeRoute
  NeulandWettbewerbRoute: typeof NeulandWettbewerbRoute
  NeulandIndexRoute: typeof NeulandIndexRoute
  NeulandGewinnerIndexRoute: typeof NeulandGewinnerIndexRoute
  NeulandGewinnerJahrSlugRoute: typeof NeulandGewinnerJahrSlugRoute
  NeulandGewinnerJahrIndexRoute: typeof NeulandGewinnerJahrIndexRoute
}

const NeulandRouteChildren: NeulandRouteChildren = {
  NeulandGewinnerInnenJahrRoute: NeulandGewinnerInnenJahrRoute,
  NeulandJuryRoute: NeulandJuryRoute,
  NeulandPresseRoute: NeulandPresseRoute,
  NeulandTeilnahmeRoute: NeulandTeilnahmeRoute,
  NeulandWettbewerbRoute: NeulandWettbewerbRoute,
  NeulandIndexRoute: NeulandIndexRoute,
  NeulandGewinnerIndexRoute: NeulandGewinnerIndexRoute,
  NeulandGewinnerJahrSlugRoute: NeulandGewinnerJahrSlugRoute,
  NeulandGewinnerJahrIndexRoute: NeulandGewinnerJahrIndexRoute,
}

const NeulandRouteWithChildren =
  NeulandRoute._addFileChildren(NeulandRouteChildren)

interface VereinBeiratRouteChildren {
  VereinBeiratIndexRoute: typeof VereinBeiratIndexRoute
}

const VereinBeiratRouteChildren: VereinBeiratRouteChildren = {
  VereinBeiratIndexRoute: VereinBeiratIndexRoute,
}

const VereinBeiratRouteWithChildren = VereinBeiratRoute._addFileChildren(
  VereinBeiratRouteChildren,
)

interface VereinVorstandRouteChildren {
  VereinVorstandIndexRoute: typeof VereinVorstandIndexRoute
}

const VereinVorstandRouteChildren: VereinVorstandRouteChildren = {
  VereinVorstandIndexRoute: VereinVorstandIndexRoute,
}

const VereinVorstandRouteWithChildren = VereinVorstandRoute._addFileChildren(
  VereinVorstandRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  JuryRoute: JuryRoute,
  KontaktRoute: KontaktRoute,
  MitgliedWerdenRoute: MitgliedWerdenRoute,
  MitgliederRoute: MitgliederRouteWithChildren,
  NeulandRoute: NeulandRouteWithChildren,
  ReferentenRoute: ReferentenRoute,
  ServiceRoute: ServiceRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnlockRoute: UnlockRoute,
  Neuland1SplatRoute: Neuland1SplatRoute,
  ProgrammSlugRoute: ProgrammSlugRoute,
  VereinBeiratRoute: VereinBeiratRouteWithChildren,
  VereinMitgliedWerdenRoute: VereinMitgliedWerdenRoute,
  VereinSatzungRoute: VereinSatzungRoute,
  VereinVorstandRoute: VereinVorstandRouteWithChildren,
  ProgrammIndexRoute: ProgrammIndexRoute,
  VereinIndexRoute: VereinIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
